#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';
$commands = require_once __DIR__ . '/config/commands.php';

use Symfony\Component\Console\Application;

$app = new Application('Console App', 'v1.0.0');
foreach ($commands as $command) {
    $app->add(new $command());
}
$app->run();